ALTER TABLE users
    ADD COLUMN IF NOT EXISTS terms_accepted_at   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS privacy_accepted_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS terms_version       VARCHAR(20) NULL;
